In [1]:
# data exploration
%reload_ext autoreload
%autoreload 2

In [35]:
import os
import spacy
import pandas as pd
import docx
import json
import utils, extract
from tqdm import tqdm


DATA_FOLDER = '/home/vishal/Documents/_practice/zycus-ml-test/data/'
TRAINING_FOLDER = os.path.join(DATA_FOLDER, 'Training_data')
VALIDATION_FOLDER = os.path.join(DATA_FOLDER, 'Validation_Data')

TRAINING_CSV_PATH = os.path.join(DATA_FOLDER, 'TrainingTestSet.csv')
VALIDATION_CSV_PATH = os.path.join(DATA_FOLDER, 'ValidationSet.csv')

In [15]:
pd.reset_option('all')
pd.set_option('display.max_colwidth', 1000)

: boolean
    use_inf_as_null had been deprecated and will be removed in a future
    version. Use `use_inf_as_na` instead.

### Open docs and align them them against target

In [10]:
def get_files_path(folder_path): # subfolder is either 
    '''get function for getting list of file paths'''
    for i in os.listdir(folder_path):
        path_to_return = os.path.join(folder_path, i)
        if os.path.isfile(path_to_return):
            yield path_to_return

training_files_path_generator = get_files_path(TRAINING_FOLDER)
training_files_path_list = [i for i in get_files_path(TRAINING_FOLDER)]

In [7]:
def get_full_text(file_path):
    document = docx.Document(file_path)
    return '\n\n'.join([para.text for para in document.paragraphs])

In [6]:
train_label_csv = pd.read_csv('../data/TrainingTestSet.csv')
train_label_csv.sample(5)

,File Name,Aggrement Value,Aggrement Start Date,Aggrement End Date,Renewal Notice (Days),Party One,Party Two
0,404_Sai Sadan_Rental Agreement,15500.0,26.06.2016,31.04.2017,30.0,Mr. RK Senthil Kumar,Mr. Sandipan Nandy Mazumdar
27,95980236-Rental-Agreement,9000.0,01.04.2010,31.03.2011,30.0,S.Sakunthala,V.V.Ravi Kian
46,269137702-Rental-Agreement,8300.0,01.04.2014,31.02.2013,30.0,Giddappa,Pottumurthi Udayalaxmi
36,195231682-This-RENTAL-AGREEMENT-is-Made-and-Ex...,13000.0,06.04.2013,05.03.2014,30.0,C.BHAGYAMMA,JP INTERIO
26,95421373-Agreement,9000.0,11.03.2012,10.02.2013,60.0,M.SANTOSH,Jeyanth B

In [11]:

training_file_names = list(map(lambda s:s.split('/')[-1].split('.')[0], training_files_path_list))
training_file_names = dict(list(zip(training_file_names, training_files_path_list)))

## sanity check: whether file names match?
# set1 = set(training_file_names); set2 = set(train_label_csv['File Name'].values)
# len(set1), len(set2), len(set1.intersection(set2)), len(set1.difference(set2)), len(set2.difference(set1))

In [12]:
combined_csv = train_label_csv.copy()
combined_csv = combined_csv[combined_csv['File Name'].isin(training_file_names)]
combined_csv['filepath'] = combined_csv['File Name'].apply(lambda x: training_file_names[x])
combined_csv['full_text'] = combined_csv.filepath.apply(lambda x: get_full_text(x))

In [16]:
combined_csv.head()

,File Name,Aggrement Value,Aggrement Start Date,Aggrement End Date,Renewal Notice (Days),Party One,Party Two,filepath,full_text
8,6683127-House-Rental-Contract-GERALDINE-GALINATO-v2-Page-1,6500.0,20.05.2007,20.05.2008,15.0,"Antonio Levy S. Ingles, Jr. and/or Mary Rose C. Ingles",GERALDINE Q. GALINATO,/home/vishal/Documents/_practice/zycus-ml-test/data/Training_data/6683127-House-Rental-Contract-GERALDINE-GALINATO-v2-Page-1.pdf.docx,"House Rental Contract\n\nKNOWN ALL MEN BY THESE PRESENTS:\n\nThis House Rental Contract, made and entered into this 20th day of May 2007 at Manila by and between:\n\nAntonio Levy S. Ingles. Jr. and/or Mary Rose C. Ingles, of legal age, with residence and postal address at Unit 2006 EGI Taft Tower 2339 Taft Avenue, Malate, Manila, And herein referred to as the Owner(s),\n\n— And —\n\nGERALDINE O. GALINATO. of legal age, with residence and postal address at 6 Manganese Road, Pilar Village, Las Pinas, Metro Manila, And herein referred to as the\n\nResident(s),\n\nWITNESSETH:\n\nIn consideration of the agreements of the Resident(s), known as: GERALDINE O. GALINATO. the Owner(s), known as: Antonio Levy S. Ingles. Jr. and/or Mary Rose C. Ingles, hereby rent their the dwelling/house located at Lot 6, Block 20, Royal South Townhomes, Marcos Alvarez Avenue, Talon 5, Las Pinas City, Metro Manila for the period commencing on the 20th day of May, 2007, and monthly thereafter until the 20th day..."
9,6683129-House-Rental-Contract-Geraldine-Galinato-v2,6500.0,20.05.2007,20.05.2008,15.0,"Antonio Levy S. Ingles, Jr. and/or Mary Rose C. Ingles",GERALDINE Q. GALINATO,/home/vishal/Documents/_practice/zycus-ml-test/data/Training_data/6683129-House-Rental-Contract-Geraldine-Galinato-v2.pdf.docx,"\n\n\n\n\n\n\n\n\n\nHouse Rental Contract\n\nKNOWN ALL MEN BY THESE PRESENTS:\n\nThis House Rental Contract, made and entered into this 20th day of May 2007 at Manila by and between:\n\nAntonio Levy S. Ingles. Jr. and/or Mary Rose C. Ingles, of legal age, with residence and postal address at Unit 2006 EGI Taft Tower 2339 Taft Avenue, Malate, Manila, And herein referred to as the Owner(s),\n\n— And —\n\nGERALDINE O. GALINATO of legal age, with residence and postal address at 6 Manganese Road, Pilar Village, Las Pinas, Metro Manila, And herein referred to as the\n\nResident(s),\n\nWITNESSETH:\n\nIn consideration of the agreements of the Resident(s), known as: GERALDINE O. GALINATO. the Owner(s), known as: Antonio Levy S. Ingles. Jr. and/or Mary Rose C. Ingles, hereby rent their the dwelling/house located at Lot 6, Block 20, Royal South Townhomes, Marcos Alvarez Avenue, Talon 5, Las Pinas City, Metro Manila for the period commencing on the 20th day of May, 2007, and monthly thereafter..."
10,18325926-Rental-Agreement-1,4000.0,05.12.2008,31.11.2009,90.0,MR.K.Kuttan,P.M. Narayana Namboodri,/home/vishal/Documents/_practice/zycus-ml-test/data/Training_data/18325926-Rental-Agreement-1.pdf.docx,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nRENTAL AGREEMENT\n\nThis deed of rental agreement executed at Bangalore this fifth day of December 2008 between MR.K.Kuttan S/o Kelu Aehari (Late) residing at site No 152 Geethalayam OMH colong S.M. Road 1st main, T.Dasarahalli, Bangalore-57. Here after called the lessor which term shall where the contest so admits mean and includes his legal heirs representatives executors and assign and Sri. P.M. Narayana Namboodri “Laxmi Leela” ground floor 3rd cross Ayyappa Nagar behind Ayyappa Temple, Jalahalli West, Bangalore - 15 referred as tenant which term shall wherever the context so admits mean and includes his legal heirs representations executors assign witnesses.\n\nWhereas the lessor is the absolute owner after premises at site No. 8/20 S.M. Road, Jalahalli West, Bangalore - 15 and he has constructed approximate 500 sft area of Ilnd floor with A.C. Sheet roof with power light in the above said premises.\n\nWhere as the owner has offered to le..."
12,36199312-Rental-Agreement,3800.0,01.05.2010,31.04.2011,30.0,Balaji.R,Kartheek R,/home/vishal/Documents/_practice/zycus-ml-test/data/Training_data/36199312-Rental-Agreement.pdf.docx,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nRENEWAL OF RENTAL AGREEMENT\n\nThis AGREEMENT of Rent is made in Bangalore and Executed today the lstth of May 2010\n\nBY AND BETWEEN\n\n1. Mr. Balaji.R\n\nAged about 63 years,\n\nNo 24 2nd Cross, SBM Colony Mathikere - 560054\n\nHereinafter referred and called as the ‘Lessor’ of the First part of one part:\n\n//AND//\n\n1 Mr.Kartheek R Aged about 31 years,\n\nNo.81, sri manjunatha nilaya, raju colony, yamalur\n\nB angalore-560037.\n\nHereinafter referred and called as the ‘Lessees’ of the second part of the another part:\n\n\nNOW THIS AGREEMENT OF RENT WITNESSETH TN AS FOLLOWS:\n\nWhereas the first party is the sole and absolute owner of the above cited / scheduled premises is hereby continued to be rented out the same to the second party which terms and conditions is as follows:\n\nThe lessor have received a security Deposit amount of Rs.40,000/- (Rupees Fourty Thousand only) f..."
13,44737744-Maddireddy-Bhargava-Reddy-Rental-Agreement,3000.0,20.09.2010,19.07.2011,NaN,M.V.V. VIJAYA SHANKAR,MADDIREDDY BHARGAVA REDDY,/home/vishal/Documents/_practice/zycus-ml-test/data/Training_data/44737744-Maddireddy-Bhargava-Reddy-Rental-Agreement.pdf.docx,"RENTfft\tENT\n\nThis Rental Agreement is made and executed on this the .?.??& day of\t\t2010 at Hyderabad, by and between:\n\nM. V, V« VI JAY A SHANKAR, S/o, M, Rangaiah\n\nR/o. Flat No. 309 , SHEETAL.ENCLAVE, JE12DIJNETLA,\t\n\nRanga Reddy Districto\n\n(Hereinafter called the “LANDLORD”)\n\nAND\n\nMADDIREDDY BHARGAVA REDDY, S/O,MADDIREDDY SUBBA REDDY, R/o,Flat No.303, SHEETAL ENCLAVE, JEEDIMETLA,\n\nRanga Reddy District\t•\n\n(Hereinafter called the “TENANT”)\n\nWHEREAS the Landlord is the absolute owner and possessor of the bearing No Flat NOe2sfi 303» sheetal enclave, jeedimetla\n\nRANGA REDDY DISTRICT\n\nWHEREAS the tenant approached the landlord and requested him/her to let-out the said House/Plot on the rental basis and the same is accepted.\n\nWHEREAS the tenant agreed to pay the monthly rent on or before\n\n5th day of every month at Rs\t9.99.7.9°\t p.m. and agreed to\n\nbear Electricity, Water Charges etc., as applicable, is valid from 11 months,.for the purposes of .Reside..."

### Seeing few of the documents

In [22]:
doc_index = 27 # change between 1-43

print('Path:', combined_csv.filepath.values[doc_index])
target_labels = dict(combined_csv.iloc[doc_index, :-2])
print(json.dumps(target_labels, indent=2))
full_text = combined_csv.full_text.values[doc_index]
utils.visualize_spacy_ents(utils.clean_text(full_text));

Path: /home/vishal/Documents/_practice/zycus-ml-test/data/Training_data/203615996-Rental-Agreement-Format.pdf.docx
{
  "File Name": "203615996-Rental-Agreement-Format",
  "Aggrement Value": 3500.0,
  "Aggrement Start Date": "01.02.2008",
  "Aggrement End Date": "31.01.2009",
  "Renewal Notice (Days)": 30.0,
  "Party One": " T.RADHA KRISHNAN ",
  "Party Two": "ABHIJIT BHARADWAJ "
}

### Analysizing patterns
Important for tagging training datasets

In [28]:
all_text_concatenated_cleaned = '\n\n'.join(combined_csv.full_text.apply(lambda x: utils.clean_text(x)))
split_paragraphs_all_cleaned = all_text_concatenated_cleaned.split('\n\n')

nlp = spacy.load('en')
spacy_docs = []
for i in tqdm(split_paragraphs_all_cleaned):
    spacy_docs.append(nlp(i))
all_ents = [(ent, ind, ent.label_) for ind, i in enumerate(spacy_docs) for ent in i.ents]
groups = utils.group_by_labels(all_ents)

In [29]:
print('Targets') ## seeing target format
combined_csv.iloc[:, 1:-2]

Targets

,Aggrement Value,Aggrement Start Date,Aggrement End Date,Renewal Notice (Days),Party One,Party Two
8,6500.0,20.05.2007,20.05.2008,15.0,"Antonio Levy S. Ingles, Jr. and/or Mary Rose C. Ingles",GERALDINE Q. GALINATO
9,6500.0,20.05.2007,20.05.2008,15.0,"Antonio Levy S. Ingles, Jr. and/or Mary Rose C. Ingles",GERALDINE Q. GALINATO
10,4000.0,05.12.2008,31.11.2009,90.0,MR.K.Kuttan,P.M. Narayana Namboodri
12,3800.0,01.05.2010,31.04.2011,30.0,Balaji.R,Kartheek R
13,3000.0,20.09.2010,19.07.2011,NaN,M.V.V. VIJAYA SHANKAR,MADDIREDDY BHARGAVA REDDY
14,700.0,15.12.2008,NaN,NaN,"PROSPER 4 LESS,LLC",Jose Luis Salcido
15,9000.0,01.04.2010,31.02.2011,60.0,P C MATHEW,L GOPINATH
16,10000.0,01.04.2010,30.03.2011,90.0,P. JohnsonRavikumar,Saravanan BV
17,8000.0,01.04.2011,31.03.2012,90.0,K. Parthasarathy,Veerabrahmam Bathini
18,5500.0,21.04.2011,19.02.2012,60.0,Asha Ramesh & Ramesh K.N,Sadasivuni Deepthi & Sadasivuni Kiran
19,6500.0,05.06.2009,04.05.2010,30.0,B. Boobalan,CHEBOLU V S R DIKSHITULU
20,4200.0,23.05.2011,22.04.2012,90.0,M.V Srinivas & M.V Madhumathi,M.V Thirumalesh
21,12000.0,NaN,NaN,30.0,Procall Private Limited,M/s Telelogic India Pvt. Ltd
22,450.0,17.08.2010,22.08.2010,NaN,Lagoon Landings LLC,John Public
23,9000.0,01.09.2011,31.08.2012,NaN,S Parthasarathy,Hari Kiran Tholeti
24,4000.0,10.05.2009,09.04.2010,90.0,E.Anwar,Mohammed Ishaq
25,450.0,08.01.2011,08.01.2012,NaN,LEE MING,JIMMY SINAU
26,9000.0,11.03.2012,10.02.2013,60.0,M.SANTOSH,Jeyanth B
27,9000.0,01.04.2010,31.03.2011,30.0,S.Sakunthala,V.V.Ravi Kian
28,12000.0,28.03.2012,31.12.2012,90.0,AR. SUBBIAH,P. SOCRATES
29,14500.0,10.01.2011,09.01.2012,90.0,Namashivayam,Thenmalar
30,600.0,NaN,NaN,NaN,Yvonne Ly,James Alan Bush
31,15000.0,11.04.2012,10.03.2013,60.0,P. Raja. Sekhar,Venkata Bhyrava Murthy Mutnuri
32,7200.0,01.03.2011,31.02.2012,30.0,k.Sarguneswaran,R.Mathankumar
34,8000.0,05.04.2011,04.04.2012,30.0,PADMAVATI,SANGHAMITRA PARIDA
35,600.0,01.09.2012,31.08.2013,30.0,ROHANI BINTI ISMAIL,SECOND PARTY
36,13000.0,06.04.2013,05.03.2014,30.0,C.BHAGYAMMA,JP INTERIO
37,3500.0,01.02.2008,31.01.2009,30.0,T.RADHA KRISHNAN,ABHIJIT BHARADWAJ
38,15000.0,23.03.2013,23.03.2014,60.0,Kamal,V.Arun Kumar
41,2500.0,01.08.2014,31.07.2015,120.0,M. Geetha,Siruvani Traders Private Limited
42,450.0,01.07.2014,31.06.2015,30.0,SUHAIMI BIN AG. AMAN AND NOOR AZEENAH BINTI MICHAEL,MOHD KHAIRUN BIN ZAKARIA
43,8000.0,01.04.2014,NaN,NaN,SHIVANAND,VIVEK CHANDRA MALLIK
44,750.0,01.04.2014,31.03.2015,NaN,NEOH GUAT WAH,NORAIDA BINTI MOHD AZHARI
45,8300.0,01.04.2014,31.02.2013,30.0,Giddappa,Pottumurthi Udayalaxmi
46,8300.0,01.04.2014,31.02.2013,30.0,Giddappa,Pottumurthi Udayalaxmi
47,7000.0,01.04.2009,31.02.2010,30.0,Parasu Ram Mishra,P.Gangadhar
48,5000.0,21.04.2014,20.09.2014,NaN,S T Nagaveni,H N Madhu
49,3500.0,17.07.2014,17.06.2015,30.0,MICHAEL DELA CRUZ,CATHERINE CABOCHA
50,NaN,NaN,NaN,NaN,N.VIJAY KUMAR,DURGA SHANKAR GUPTA
51,800.0,01.04.2016,NaN,30.0,RC AND PAUL PAULINO,NaN
52,22000.0,16.07.2011,16.10.2011,NaN,MARITES M. ALICANTE,JASMIN B. BAKER and EDWARD RAY BAKER
53,11500.0,01.05.2016,31.03.2015,30.0,ANAND RAJ,BEENA PURATHAYIL MADHAVAN
54,23000.0,01.09.2018,31.08.2021,90.0,PARMESHWARI DEVI JOSHI,TECHNOCULTURE BUILDING CENTRE PRIVATE LIMITED

In [31]:
{i:j for i, j in groups.items() if i in ['PERSON', 'PRODUCT']} # first item is extracted text, second is paragraph number

{'PERSON': [(Antonio Levy S. Ingles, 1),
  (Jr., 1),
  (Mary Rose C. Ingles, 1),
  (O. GALINATO, 2),
  (Metro Manila, 2),
  (GERALDINE O. GALINATO, 3),
  (Antonio Levy S. Ingles, 3),
  (Jr., 3),
  (Mary Rose C. Ingles, 3),
  (Marcos Alvarez Avenue, 3),
  (Metro Manila, 3),
  (JR, 9),
  (Antonio Levy S. Ingles, 11),
  (Jr., 11),
  (Mary Rose C. Ingles, 11),
  (O. GALINATO, 12),
  (Metro Manila, 12),
  (GERALDINE O. GALINATO, 13),
  (Antonio Levy S. Ingles, 13),
  (Jr., 13),
  (Mary Rose C. Ingles, 13),
  (Marcos Alvarez Avenue, 13),
  (Metro Manila, 13),
  (JR, 20),
  (Singular, 61),
  (Feminine, 61),
  (Lesser, 61),
  (Tenant, 61),
  (Antonio Levy S. Ingles, 65),
  (Marcos Alvarez Avenue, 68),
  (Metro Manila, 68),
  (Metro Manila, 69),
  (JR, 69),
  (Marcos Alvarez Avenue, 69),
  (Metro Manila, 69),
  (Resident(s)/, 72),
  (Marcos Alvarez Avenue, 72),
  (Metro Manila, 72),
  (P.M. Narayana Namboodri Laxmi Leela, 73),
  (Ayyappa Nagar, 73),
  (Balaji, 88),
  (Colony Mathikere - 560054, 88),
  (Kartheek, 90),
  (sri manjunatha nilaya, 90),
  (raju colony, 90),
  (yamalur, 90),
  (Lessees, 98),
  (sri manjunatha nilaya, 100),
  (raju colony, 100),
  (yamalur Bangalore-560037, 100),
  (M. V, 103),
  (Ranga Reddy Districto, 105),
  (MADDIREDDY BHARGAVA REDDY, 105),
  (Ranga Reddy District, 106),
  (Jose Luis Salcido, 113),
  (Resident, 113),
  (Kerosene Heaters and, 132),
  (Kerosene, 132),
  (Resident, 146),
  (lien, 148),
  (Resident, 148),
  (Resident, 156),
  (herein, 162),
  (P C MATHEW, 163),
  (L GOPINATH, 163),
  (VALLUVAR, 164),
  (P. JohnsonRavikumar, 182),
  (Lakshmipuram Tiruvanmiyur, 182),
  (Saravanan BV, 183),
  (Lakshmipuram Tiruvanmiyur, 183),
  (Lakshmipuram Tiruvanmiyur, 185),
  (Tenant, 190),
  (K. Parthasarathy, 197),
  (Veerabrahmam Bathini, 198),
  (Lingaiah Bathini, 198),
  (LESSEE, 198),
  (Krishna Krupa, 199),
  (Krishna Krupa, 200),
  (Lessee, 201),
  (VHBCSL Layout, 211),
  (K.N. Residing, 212),
  (Deepti Mr, 213),
  (Sadasivuni Kiran, 213),
  (LESSEE, 213),
  (LESSEE, 214),
  (LESSEE, 216),
  (LESSEE, 217),
  (Tenancy, 218),
  (LESSEE, 219),
  (LESSEE, 219),
  (LESSEE, 220),
  (LESSEE, 223),
  (LESSEE, 224),
  (LESSEE, 225),
  (B. Boobalan, 228),
  (Okkiyam Pettai, 228),
  (PTC Quarters, 228),
  (CHEBOLU, 228),
  (Okkiyam Pettai, 228),
  (PTC Quarters, 228),
  (Owner, 231),
  (Owner, 233),
  (Owner, 234),
  (M.V. Thirumalesh, 242),
  (Owner, 244),
  (Owner, 246),
  (Tenant, 254),
  (Compensation, 254),
  (Tenant, 254),
  (Shiekh Sarai, 262),
  (Procall, 263),
  (User, 264),
  (Procall, 267),
  (Procall, 271),
  (W.D.V, 272),
  (Procall, 273),
  (Procall, 291),
  (Authorised Signatory, 298),
  (John Public, 299),
  (Lagoon Landings LLC, 299),
  (Add Cleaning Fee, 299),
  (Tenant, 311),
  (Lagoon Landings LLC, 323),
  (S Parthasarathy, 325),
  (Film Nagar, 325),
  (Hyderabad - 500096, 325),
  (Hari Kiran, 325),
  (Sri Venkateswara Residency, 325),
  (S Parthasarathy, 326),
  (Kendriya Vihar, 326),
  (Yelahanka, 326),
  (Owner, 327),
  (Tenant, 327),
  (Tenant, 327),
  (Owner, 327),
  (Owner, 329),
  (Owner, 331),
  (Owner, 332),
  (Tenant, 336),
  (Owner, 336),
  (Owner, 337),
  (Owner, 339),
  (Tenant, 340),
  (Tenant, 341),
  (Owner, 341),
  (Mohammed Ishaq s/, 346),
  (Mohammed Moosa, 346),
  (Lessor, 347),
  (Ground Floor, 361),
  (LEE MING, 364),
  (RM450, 369),
  (Mr M.SANTOSH S/O.M.DATTATREYA, 379),
  (pearl, 380),
  (Nagar, 380),
  (LANDLORD, 380),
  (Jeyanth B, 381),
  (Iyyappa Nagar, 381),
  (Madipakkam Chennai - 91, 381),
  (Woodwork, 392),
  (almirah slabs, 392),
  (Granite, 392),
  (LANDLORD, 393),
  (Said Noise, 397),
  (S.Sakunthala, 408),
  (Nagar, 409),
  (Hyderabad Andhra Pradesh.-36, 409),
  (Schedule, 410),
  (AR, 423),
  (Anandaraja Nagar, 423),
  (S.Kodikulam, 423),
  (P. SOCRATES, 424),
  (Jains Sudharshana, 427),
  (28.03.2012, 428),
  (Jains Sudharshana, 441),
  (Rajakilpakkam, 441),
  (Kamaraj Nagar, 443),
  (Pudukkottai, 443),
  (Kamaraj Nagar, 445),
  (WRITTEN, 460),
  (miuj Ume, 475),
  (houXehold, 478),
  (22.01.2013, 484),
  (.P, 485),
  (Owner, 491),
  (Venkateswara nagar, 512),
  (Tamil Nadu, 512),
  (Ramasamy, 513),
  (Madha kovil, 513),
  (Owner, 514),
  (Venkateswara nagar, 514),
  (Tamil Nadu, 514),
  (Owner, 517),
  (Owner, 519),
  (Tenant, 519),
  (Tenant, 520),
  (Owner, 520),
  (Owner, 521),
  (G M Palya, 527),
  (SANGHAMITRA PARIDA, 528),
  (Ground, 529),
  (G M Palya, 529),
  (Rs.60000/-, 532),
  (Tenancy, 532),
  (Tenancy, 533),
  (Tenant, 535),
  (Owner, 535),
  (Tenant, 535),
  (Owner, 535),
  (G M Palya, 541),
  (Bath Toilet, 541),
  (DARUL AMAN MALAYSIA, 543),
  (DARUL AMAN, 546),
  (31.08.2013, 548),
  (RM1100.00(RINGGIT MALAYSIA, 553),
  (Smt C.BHAGYAMMA, 559),
  (Manjeera Nagar, 559),
  (Sangareddy Mandal, 559),
  (Ramachandrapuram, 561),
  (Sharada Hema, 563),
  (Galaxy, 563),
  (Situated Chandanagar, 563),
  (Ranga Reddy District, 563),
  (Sharada Hema, 564),
  (Durga Galaxy, 564),
  (Situated Chandanagar, 564),
  (Ranga Reddy District, 564),
  (Andhra Pradesh, 564),
  (Flat NO.204, 565),
  (Sharada Hema, 565),
  (Ranga Reddy District, 565),
  (Andhra Pradesh, 565),
  (Tidy, 575),
  (T.RADHA KRISHNAN, 578),
  (Murugeshpalya, 578),
  (Murugeshpalya, 594),
  (Kamal, 601),
  (Appar Sundar, 601),
  (Pursawalkam, 601),
  (Kosapt, 601),
  (Appar, 601),
  (Pursawalkam, 601),
  (Veda Chalam, 602),
  (Kanda Swamy Koil, 603),
  (Pursawalkam Chennai, 603),
  (LESSEE, 604),
  (LESSEE, 609),
  (LESSEE, 611),
  (LESSEE, 612),
  (Kamal, 612),
  (LESSEE, 613),
  (LESSEES, 613),
  (LESSEE, 614),
  (LESSEE, 615),
  (LESSEE, 616),
  (LESSEE, 616),
  (LESSEE, 617),
  (LESSEE, 618),
  (LESSEE, 619),
  (LESSEE, 619),
  (LESSEE, 620),
  (LESSEE, 621),
  (Kamal, 621),
  (LESSEE, 621),
  (LESSEE, 623),
  (LESSEE, 624),
  (LESSEE, 625),
  (LESSEE, 625),
  (LESSEE, 626),
  (LESSEE, 627),
  (LESSEE, 631),
  (SIGNATURE, 633),
  (M. Geetha, 636),
  (V. Manoharan, 636),
  (Saravana Flats, 636),
  (Devaki Nagar, 636),
  (J. L. Saravana, 637),
  (Muthurangam Block, 637),
  (Ashok Nagar, 637),
  (M. Geetha, 638),
  (Saravana Flats, 638),
  (Devaki Nagar, 638),
  (Saravana Flats, 642),
  (Devaki Nagar, 642),
  (MICHAEL, 657),
  (JOINTLY, 682),
  (Jalan Baru Kg, 684),
  (Benoni, 684),
  (Request number(SRF, 693),
  (FIFTY THOUSAND, 696),
  (Geyser, 703),
  (Rs.20/-, 704),
  (Landlord, 709),
  (pada minggu pertama, 718),
  (Landlord, 721),
  (rumah kecuali, 723),
  (mendapat kebenaran daripada, 723),
  (tuan rumah, 723),
  (Segala, 726),
  (dan arnab, 726),
  (Mana-mana, 733),
  (kimia adalah dilarang, 733),
  (adalah dilarang, 734),
  (Lilin, 734),
  (Lilin, 734),
  (kawasan yang, 734),
  (dan perlu, 734),
  (yang boleh, 737),
  (jiran, 737),
  (ancaman keganasan tidak dibenarkan, 739),
  (Keys, 744),
  (bilik kosong, 749),
  (sesiapa pun pada bila-bila masa, 749),
  (Pemilik rumah, 751),
  (secara berkala, 751),
  (rumah, 751),
  (dan jika, 751),
  (dan pajakan itu hendaklah, 751),
  (Jika longkang, 753),
  (tuala wanita, 753),
  (mainan kanak-kanak, 753),
  (wads kertas, 753),
  (gris, 753),
  (sisa meja, 753),
  (dan Iain-lain, 753),
  (Penyewa, 753),
  (membayar kos pembersihan, 753),
  (pada mana-mana, 756),
  (bangunan tanpa kebenaran dari, 756),
  (pemilik rumah, 756),
  (Rumah ini khususnya, 757),
  (Sila tulis dan, 759),
  (ruang yang, 759),
  (bawah sebagai petunjuk, 759),
  (anda telah, 759),
  (dan memahami peraturan-peraturan, 759),
  (Nagappa D, 765),
  (Main Bazar, 766),
  (Miryalaguda, 766),
  (Tenancy, 772),
  (ohanchi h/o, 777),
  (Ran Krishna, 784),
  (Miryalaguda, 785),
  (Tenancy, 791),
  (Tenant, 792),
  (RarrH.murthyrvagar, 796),
  (Parasu Ram Mishra, 799),
  (D.no, 799),
  (P.Gangadhar Working, 801),
  (D.no:15/5/2 KAUSTHUBHA, 804),
  (B.T.M - STAGE 2, 804),
  (Lessor, 819),
  (NONACC, 820),
  (BK)/, 820),
  (Bill, 828),
  (Tumkur Taluk, 830),
  (Gukur Hobli, 830),
  (MICHAEL DELA, 884),
  (Landlord, 919),
  (Landlord, 934),
  (Tenant, 937),
  (M. ALICANTE, 942),
  (JASMIN B. BAKER, 943),
  (LANDLORD, 965),
  (LANDLORD, 966),
  (LANDLORD, 967),
  (TENANT, 968),
  (LANDLORD, 972),
  (LANDLORD, 972),
  (M. ALICANTE LANDLORD, 976),
  (BAKER, 976),
  (MARITES M. ALICANTE              , 977),
  (JASMIN B. BAKER              , 977),
  (ANAND RAJ, 980),
  (Alakode, 980),
  (LESSEE, 980),
  (MADHAVAN W/, 980),
  (Nandavanam, 980),
  (Chcmbumukku, 980),
  (Thrikkakara P O. Cochin 682021, 980),
  (Regal Valancia, 981),
  (Joshi Kunj, 999),
  (Akashwani, 999),
  (Late Phulman Sunwar, 1001),
  (Junglee Mohal, 1001),
  (P.S. Bhaktinagar, 1001),
  (Owner, 1002),
  (Opposite Akashvani Bhawan, 1002),
  (P.S. Bhaktinagar, 1002),
  (Schedule, 1002),
  (LESSEE, 1003),
  (LESSEE, 1004),
  (LESSEE, 1004),
  (LESSEE, 1005),
  (LESSEE, 1006),
  (Build, 1006),
  (Schedule, 1006),
  (LESSEE, 1007),
  (LESSEE, 1011),
  (LESSEE, 1012),
  (LESSEE, 1014),
  (LESSEE, 1016),
  (LESSEE, 1017),
  (LESSEE, 1018),
  (LESSEE, 1018),
  (LESSEE, 1020),
  (LESSEE, 1021),
  (LESSEE, 1022),
  (LESSEE, 1023),
  (LESSEE, 1023),
  (LESSEE, 1024),
  (LESSEE, 1025),
  (LESSEE, 1026),
  (Lessor, 1028),
  (Siliguri, 1029),
  (P.S. Bhaktinagar, 1030),
  (Joshi Kunj, 1031)],
 'PRODUCT': [(ST ARUMBAKKAM CHENNAI 600106, 164),
  (Chennai - 600 041, 182),
  (041, 185),
  (Geezer, 227),
  (Scheduled, 253),
  (Taxes, 277),
  (Taxes, 292),
  (Landlords, 311),
  (615-599-4092, 323),
  (Premises, 341),
  (Lessee, 347),
  (Lessee, 348),
  (Lessee, 355),
  (Lessor and Lessee, 363),
  (THE OTHER PART, 381),
  (LANDLORD, 393),
  (Lessee, 411),
  (Madurai - 625 007, 423),
  (Owner of the FIRST PART, 423),
  (Last mop(srent, 470),
  (LANGKAWI, 544),
  (RM600-00, 550),
  (Galaxy, 565),
  (Shri ram shankari Apt, 580),
  (012, 601),
  (23.03.14, 607),
  (Refer Point 16, 611),
  (Chennai - 600, 637),
  (Keys, 686),
  (RM300, 719),
  (Schedule, 774),
  (rr.aXe, 792),
  (Landlords, 933),
  (Landlords, 933),
  (Landlords, 933),
  (Landlords, 936),
  (Landlords, 937),
  (TENANTS, 970),
  (LANDLORD, 970),
  (Lessee, 981),
  (Lessee, 1013),
  (legal/ Government/, 1023)]}

In [32]:
print('See date patterns')
{i:j for i, j in groups.items() if i in ['DATE']} # first item is extracted text, second is paragraph number

See date patterns

{'DATE': [(this 20th day, 0),
  (May 2007, 0),
  (2006, 1),
  (the 20th day of May, 2007, 3),
  (monthly, 3),
  (the 20th day of May, 2008, 3),
  (the 20th day of every month, 5),
  (monthly, 6),
  (month, 6),
  (at least 7 days, 9),
  (monthly, 9),
  (3 day, 9),
  (this 20th day, 10),
  (May 2007, 10),
  (2006, 11),
  (the 20th day of May, 2007, 13),
  (monthly, 13),
  (the 20th day of May, 2008, 13),
  (the 20th day of every month, 15),
  (monthly, 18),
  (month, 18),
  (at least 7 days, 20),
  (monthly, 20),
  (3 day, 20),
  (3 days, 38),
  (15 days, 48),
  (one months, 49),
  (at least 15 days, 49),
  (monthly, 49),
  (the 20th day of May, 2008, 49),
  (Thirty days, 50),
  (at least 7 days, 50),
  (this 2007, 64),
  (monthly, 69),
  (June 20, 2007, 69),
  (May 20, 2007, 69),
  (June 20, 2007, 70),
  (May 20, 2007, 70),
  (this 20th day of May, 2007, 72),
  (this fifth day of December 2008, 73),
  (Four Thousand, 75),
  (eleven months, 76),
  (every eleventh month, 76),
  (10th of each month, 77),
  (three month, 79),
  (one week, 80),
  (today, 87),
  (May 2010, 87),
  (BETWEEN 1, 88),
  (about 63 years, 88),
  (24 2nd, 88),
  (about 31 years, 90),
  (11) months, 96),
  (one month, 97),
  (the day month year, 101),
  (this the .. day of        2010, 102),
  (monthly, 108),
  (5th day of every month, 109),
  (this 11 day of December, 2008, 112),
  (the 15 day of DECEMBER, 2008, 115),
  (7) days, 116),
  (monthly, 120),
  (14 days, 123),
  (monthly, 123),
  (the beginning date, 123),
  (monthly, 130),
  (1980, 141),
  (3) days, 143),
  (the last sixty, 147),
  (60) days, 147),
  (7) days, 149),
  (years, 152),
  (the day and year, 162),
  (21st OF MARCH 2010, 163),
  (monthly, 164),
  (monthly, 164),
  (1st April 2010, 164),
  (monthly, 165),
  (a period of, 165),
  (11 months, 165),
  (1st of April 2010, 165),
  (month, 165),
  (a period of, 166),
  (11 months, 166),
  (this day, 1st of April 2010, 166),
  (monthly, 168),
  (Two months, 176),
  (two month, 177),
  (the expiry of eleven months, 178),
  (one month, 178),
  (THE DAY AND, 181),
  (14th day of July 2010, 182),
  (about 43 Years, 182),
  (about 27 years, 183),
  (monthly, 185),
  (a period of, 187),
  (11 months, 187),
  (monthly, 188),
  (Ten Thousand, 188),
  (month, 188),
  (three months, 195),
  (the day, 196),
  (this 1st day April two thousand eleven, 197),
  (about 75 years, 197),
  (about 28 years, 198),
  (monthly, 201),
  (monthly, 201),
  (a period of twelve months, 203),
  (three months, 210),
  (20 April 2011, 212),
  (82A, 212),
  (53-38-20, 213),
  (monthly, 215),
  (monthly, 216),
  (months, 218),
  (monthly, 219),
  (monthly, 219),
  (100/month, 219),
  (daily, 220),
  (months, 221),
  (12 months, 222),
  (2 months, 224),
  (this 5th day of JUNE 2009, 228),
  (about 40 years, 228),
  (about 22 years, 228),
  (monthly, 230),
  (Six Thousand and, 230),
  (10th of every month, 230),
  (a period of 11 months, 232),
  (the month, 232),
  (a consecutive period of 3 months, 233),
  (one month, 236),
  (the day,month, 239),
  (year first, 239),
  (23 rd day of May Two Thousand Eleven, 240),
  (54 years 42 Years, 241),
  (about 32 years, 242),
  (this day, 246),
  (monthly, 247),
  (a period of 2 months, 249),
  (every one year, 250),
  (Three months, 254),
  (Months, 256),
  (the day, month, 261),
  (year, 261),
  (a minimum period of 12 months, 268),
  (a minimum period of, 270),
  (months, 270),
  (monthly, 276),
  (one month, 279),
  (monthly, 280),
  (12 months, 285),
  (30 days, 285),
  (months, 285),
  (the balance months, 285),
  (1881, 288),
  (1996, 289),
  (the period of 12 months, 292),
  (this day, month, 295),
  (year, 295),
  (this 19 day of August, 2010, 299),
  (23432, 299),
  (8/17/2010, 299),
  (8/22/2010, 299),
  (14 days, 300),
  (daily, 303),
  (daily, 303),
  (37064, 323),
  (this first day of September 2011, 325),
  (01-09-2011, 325),
  (69 years, 325),
  (36 years, 325),
  (Bangalore- 560064, 326),
  (monthly, 327),
  (Clause 4, 327),
  (Clause 3, 327),
  (1st September 2011, 328),
  (eleven) months, 328),
  (monthly, 329),
  (month, 329),
  (day, 331),
  (Clause 1, 338),
  (eleven months, 338),
  (2009, 344),
  (monthly, 348),
  (Months, 349),
  (the date of 10/05/2009, 349),
  (every 11 months, 349),
  (three months, 351),
  (3 months, 354),
  (2nd, 361),
  (1-Fan, 1-Geyser, 363),
  (the day,month, 363),
  (year first, 363),
  (521212-01-6009, 364),
  (58-01-02, 366),
  (1-8-2011, 367),
  (monthly, 368),
  (the First day of each month, 368),
  (three weeks, 370),
  (at least one day, 372),
  (this the 15th day of February 2012, 378),
  (31 years, 379),
  (30 years, 381),
  (Eleven) months, 385),
  (11th day of March 2012 to 10th day of February 2013, 385),
  (monthly, 389),
  (Eleven) months, 400),
  (Eleven) months, 401),
  (2 months, 401),
  (2 months, 401),
  (30 day, 402),
  (this day, 404),
  (the date, month, 406),
  (year first, 406),
  (this the 1st, 407),
  (May 2005, 407),
  (Eleven) months, 412),
  (1st April 2010, 412),
  (monthly, 412),
  (monthly, 413),
  (every month, 413),
  (tenth day of subsequent month, 413),
  (one month, 419),
  (three months, 420),
  (the day, month, 422),
  (year, 422),
  (this 28th day of March, 2012, 423),
  (about 49 years, 423),
  (about 36 years, 424),
  (monthly, 428),
  (this day, 428),
  (the period ending 31st December 2012, 428),
  (31st December 2012, 428),
  (Two Thousand Five Hundred, 431),
  (month, 431),
  (every month, 432),
  (290173, 433),
  (THREE MONTHS, 438),
  (THE DAY, 442),
  (YEAR FIRST, 442),
  (Jan 10, 2011, 443),
  (Jan 10 2011, 445),
  (monthly, 445),
  (twelve months, 445),
  (12 months, 446),
  (three months, 448),
  (a month, 449),
  (that month, 449),
  (annual, 450),
  (Jan 10, 2011, 457),
  (Month, 460),
  (30) days, 460),
  (no less than 7 days, 460),
  (monthly, 461),
  (monthly, 463),
  (monthly, 464),
  (monthly, 465),
  (monthly, 466),
  (days, 470),
  (three weeks, 472),
  (annually, 473),
  (last months, 473),
  (1978, 481),
  (1978, 483),
  (monthly, 493),
  (a period of, 495),
  (eleven months, 495),
  (monthly, 497),
  (every succeeding month, 499),
  (month, 504),
  (the agreed period of, 507),
  (eleven months, 507),
  (1st day of September 2011, 511),
  (about 54 years, 512),
  (28 years, 513),
  (monthly, 516),
  (5 th day of every month, 516),
  (a period of, 518),
  (eleven months, 518),
  (a consecutive period of two or more months, 519),
  (one month, 524),
  (the day, 526),
  (the month the year first, 526),
  (this 5th day of April, 2012, 527),
  (monthly, 531),
  (10 after 11 months, 531),
  (11) Months, 533),
  (April of 2012, 533),
  (a consecutive period of two months, 534),
  (one-month, 538),
  (one month, 539),
  (the day and year first, 542),
  (15 SEPTEMBER 2012, 543),
  (monthly, 547),
  (12 months, 548),
  (monthly, 549),
  (Six Hundreds, 549),
  (RM500-00, 550),
  (monthly, 550),
  (monthly, 552),
  (monthly, 552),
  (monthly, 554),
  (one month, 554),
  (ONE calendar month, 556),
  (ONE month, 556),
  (06th day of March 2013, 558),
  (age about 52 years, 559),
  (about 33 years, 561),
  (a period of, 567),
  (11 months, 567),
  (06th day of April 2013, 567),
  (monthly, 568),
  (the 10th day of same month, 568),
  (ONE month, 571),
  (all seasons, 575),
  (this the 1st day of February 2008, 577),
  (monthly, 584),
  (a period of, 586),
  (1st day of February 2008, 586),
  (the month, 586),
  (a consecutive period of three months, 587),
  (One month, 591),
  (the expiry of 11 months, 593),
  (the day, month, 597),
  (year first, 597),
  (the March 22nd day 2013, 600),
  (about 32 years, 601),
  (about 62 years, 601),
  (Monthly, 604),
  (a period of 12 months, 604),
  (monthly, 604),
  (a period of 12 months, 606),
  (12 months, 607),
  (Monthly, 609),
  (15000.00 per month, 610),
  (100000, 611),
  (monthly, 612),
  (1000 per month, 612),
  (monthly, 616),
  (two consecutive months, 616),
  (monthly, 621),
  (Levies, 622),
  (Two) months, 625),
  (monthly, 625),
  (the period of two months, 625),
  (12 / 24 months, 628),
  (the day, 631),
  (month and year first, 632),
  (this 19th day of August 2013, 635),
  (about 53 years, 636),
  (about 33 years, 637),
  (monthly, 642),
  (11 Months, 643),
  (August 2014, 643),
  (4 months, 653),
  (every 11 months, 655),
  (THE DAY AND, 656),
  (RM 450 per month, 658),
  (1st July 2014, 659),
  (1) year, 659),
  (month, 659),
  (the First Months, 661),
  (RM 450, 661),
  (2 months, 661),
  (RM 350, 661),
  (RM 1700, 661),
  (30 days, 662),
  (14 days, 664),
  (30 day, 666),
  (three day, 669),
  (30-day, 673),
  (month, 674),
  (month, 674),
  (89607, 684),
  (Monthly, 695),
  (2working days, 705),
  (75250, 710),
  (1st JANUARY 2014, 711),
  (1 Year, 711),
  (TWO MONTHS months, 712),
  (DECEMBER, 712),
  (2013, 712),
  (1st JANUARY 2014, 712),
  (TWO MONTHS, 713),
  (1 Month, 713),
  (the month of JANUARY, 713),
  (2014, 714),
  (1 Month, 715),
  (the last month, 715),
  (Oil every first week, 716),
  (the first months, 744),
  (820416-01-5972, 761),
  (month, 771),
  (months, 771),
  (Two Month, 772),
  (184 1st floor 2nd, 776),
  (the day,month, 778),
  (year first, 778),
  (2003, 779),
  (2nd, 783),
  (5600 16, 783),
  (Eleven) months, 790),
  (No.184 1st floor 2nd, 795),
  (the day.month end year, 797),
  (this 1st day, 798),
  (April,2009(01-04-2009, 798),
  (monthly, 806),
  (every month, 806),
  (monthly, 807),
  (months, 809),
  (every 11 months 5, 809),
  (one month, 815),
  (one month, 815),
  (one month, 817),
  (R.C.C.roofed, 818),
  (the day month and year first, 819),
  (Two thousand fourteen April twenty first, 822),
  (this day, 825),
  (monthly, 826),
  (05 months, 827),
  (monthly, 829),
  (every year, 829),
  (over 12 months, 829),
  (1) year, 834),
  (1) year, 834),
  (one month, 834),
  (monthly, 835),
  (monthly, 835),
  (one month, 836),
  (one month, 836),
  (1 day, 844),
  (2 days, 845),
  (at least 14 days, 871),
  (more than 2 months, 873),
  (the final day, 875),
  (September 17, 2014, 878),
  (October 17, 2014, 878),
  (November 17, 2014, 878),
  (December 17,, 878),
  (the 27th day January 2010, 885),
  (about 51 years, 886),
  (monthly, 889),
  (11 month, 890),
  (one month, 890),
  (the period of 11 month, 891),
  (11 month, 892),
  (three months, 895),
  (1 month, 898),
  (No.9 18th, 906),
  (the day, month, 909),
  (year first, 909),
  (this 27TH Day of MARCH 2016, 910),
  (96818, 912),
  (month to month, 913),
  (APRIL 1, 913),
  (month, 913),
  (at least 30 days, 913),
  (monthly, 914),
  (the 1st day of each month, 914),
  (The first months, 914),
  (7 days, 917),
  (the 8th of the month, 917),
  (30), 919),
  (30 days, 919),
  (30) days, 920),
  (15 days, 923),
  (that month, 923),
  (previous months, 923),
  (3 days, 926),
  (3-day, 935),
  (45 days, 938),
  (this 19th day of July, 2011, 941),
  (50-20th, 942),
  (2-Lot 7, 943),
  (2-Lot 7, 945),
  (3) MONTHS, 949),
  (16 July 2011 to 16 October 2011, 949),
  (7) days, 949),
  (monthly, 950),
  (1) month, 952),
  (2) months, 952),
  (August 6, 2011, 952),
  (3) MONTHS, 952),
  (6 August 2011, 953),
  (2) months, 953),
  (monthly, 953),
  (21 days, 955),
  (next monthly, 956),
  (16 August 2011, 956),
  (1) month, 957),
  (14 days, 962),
  (7 days, 966),
  (those many days, 966),
  (19 July 2011, 975),
  (the 1st day of May 2016, 980),
  (26 years, 980),
  (62 years, 980),
  (Thrikkakara- 682021, 981),
  (monthly, 982),
  (11 months, 989),
  (01-05-2016, 989),
  (this day, 989),
  (one month, 992),
  (the day month and year first, 996),
  (2018, 999),
  (TWO THOUSAND EIGHTEEN, 999),
  (36, 1005),
  (Thirty Six) months, 1005),
  (1st September 2018, 1005),
  (Six) months, 1006),
  (the 1st September 2018, 1006),
  (Six) months, 1009),
  (1st September 2018, 1009),
  (monthly, 1010),
  (Six) months, 1010),
  (monthly, 1011),
  (the - succeeding month, 1011),
  (only per month, 1012),
  (31st August, 1014),
  (one month, 1014),
  (Page - 5, 1027),
  (31st August 2021, 1027),
  (months, 1028),
  (one month, 1028),
  (the day month, 1032)]}

### Extract patterns

In [1069]:
#lets see extractive capacity
subject_strings = [i.lower() for i in split_paragraphs_all_cleaned]
# regex_pattern = regex_pattern2
# extracted_spans = get_index_of(regex_pattern3, subject_strings)

In [1054]:
# [(i, get_time_delta(i)) for i, j, k in extracted_spans]
# # extracted_text = '20th day of may 2007'
# [(i, get_normal_from_text(i)) for i, j, k in extracted_spans]


# extracted_spans

In [51]:
def get_candidates(text):
    candidates_for_date = extract.extract_date_spans(text)
    candidates_for_date =[[text[start:end], (start, end), 1]\
                           for start, end in extract.extract_continuous_span(candidates_for_date)]
        
    candidates_for_timedelta = extract.extract_timedelta(text)
    
    candidates_for_amount = extract.extract_continuous_span(extract.extract_amount_spans(text))
    candidates_for_amount =[[text[start:end], (start, end), 1]\
                           for start, end in extract.extract_continuous_span(candidates_for_amount)]
    
    candidates_for_name = extract.extract_name_spans(text)
    
    return dict(date=candidates_for_date, timedelta=candidates_for_timedelta, 
               amount=candidates_for_amount, name=candidates_for_name)

In [ ]:
def normalize_date(dates):
    formated_dt_index = pd.to_datetime(dates, dayfirst=True)
    year = formated_dt_index.year
    month = formated_dt_index.month
    day = formated_dt_index.day
    
    triplets_of_day_month_year = list(zip(day, month, year))
    triplets_of_day_month_year = [list(map(int, i)) if all([float(j).is_integer() for j in i]) else None \
                                   for i in triplets_of_day_month_year]
    return triplets_of_day_month_year

In [ ]:
get_candidates[]

In [39]:
one_doc_full_text = utils.clean_text(combined_csv.full_text[27])

In [41]:
print(one_doc_full_text)

RENTAL AGREEMENT This Rental Agreement is made and executed at Bangalore on this the 1st May 2005 by and between:

Mrs. S.Sakunthala, Hno: 4E,10-12-1, REDNAM ALCAZAR, Opp. SBI Main, Old Jail Road Jn, Vishakapatnam - 530020 Hereinafter called as the LESSOR (which expression shall mean and include wherever the context so requires admits his heirs, executors, representatives and assigns) of the ONE PART

And: V.V.Ravi Kian S/o V.R.G.Sastry, A.S.Rao Nagar, Hyderabad Andhra Pradesh.-36 Hereinafter called the LESSEE (Which expression shall mean and include wherever the context so requires, admits his executors, representatives and assigns) of the OTHER PART.

WITNESSES AS FOLLOWS: Whereas the Lessor is the absolute owner of the Fourth Floor residential premises bearing No:407A, T.C.Palya Main Road, Ram murthy nagar, Bangalore-16, which are morefully described in the Schedule written here under and hereinafter referred to as the Schedule Property.

Whereas the Lessor has agreed to grant a lease of the said premises to the Lessee under the following terms and conditions.

DURATION: The duration of the Lease shall be for a period of 11 (Eleven) months commencing from 1st April 2010 and is subject to renewal thereafter under mutually agreed terms and conditions by the Lessor and the Lessee with an enhancement of 5 in the monthly rent.

RENT: The monthly rent payable by the Lessee to the LESSOR for the Schedule Property shall be Rs. 9,000/- (Nine thousand and two hundred rupees only). This amount shall be paid every month within tenth day of subsequent month.

ELECTRICITY AND WATER CHARGES: The Lessee shall pay the Electricity charges to the concerned department regularly

INTERNAL MAINTENANCE: The Lessee shall maintain the Schedule Property in a state of good order and condition and shall not cause any damage or disfigurement to the schedule property there in always expecting fair wear and tear.

LIABLE FOR DAMAGES: It is agreed that any damages caused by the Lessee in the Schedule Property shall be made good by the Lessee promptly.

USER: The Schedule Property shall be used by the Lessee only for residential purpose and shall not use or permit the same for any business or occupation or any unlawful purpose.

DEPOSIT: The Lessee has paid a sum of Rs. 80,000/- (Rs. Eighty thousand only) by way of cash as Security Deposit. The same amount shall be refundable by the Lessor to the Lessee without any interest at the time of vacating the Schedule Premises.

TERMINATION OF LEASE: Either party may give one month notice in writing to terminate this Lease agreement.

Notwithstanding what is stated above, the agreement shall be revoked by the Lessor, if the Lessee is in default in the payment of the rent and/or other charges three months after the same have fallen due or if the Lessee commits breach of any terms and conditions of this agreement.

SCHEDULE PROPERTY Fourth Floor of the residential premises situated at HNO:407 A, T.C. Palya Main Road, Ram murthy nagar, Bangalore-560037, Consisting of three Bedrooms, hall, kitchen, two attached Toilet and Bathrooms.

Fittings and Fixtures: In WITNESS WHEREOF the parties have executed this agreement in the presence of the following witnesses on the day, month and year as first above mentioned.

In [63]:
get_candidates(one_doc_full_text)

{'date': [[85, 97], [142, 149], [1177, 1191]],
 'timedelta': [],
 'amount': [[85, 86],
  [93, 97],
  [139, 149],
  [216, 222],
  [395, 398],
  [483, 485],
  [732, 736],
  [777, 780],
  [832, 834],
  [1142, 1152],
  [1177, 1178],
  [1187, 1191],
  [1324, 1325],
  [1446, 1468],
  [1473, 1484],
  [2281, 2287],
  [2295, 2310],
  [2530, 2533],
  [2754, 2759],
  [2896, 2900],
  [2953, 2956],
  [3010, 3016],
  [3032, 3037],
  [3063, 3066],
  [3272, 3275]],
 'name': [[RENTAL AGREEMENT, (0, 16), 1],
  [This Rental Agreement, (17, 38), 1],
  [Bangalore, (63, 72), 1],
  [Mrs. S.Sakunthala, Hno: 4E,10-12-1, REDNAM ALCAZAR, (115, 165), 1],
  [S.Sakunthala, (120, 132), 1],
  [REDNAM ALCAZAR, (151, 165), 1],
  [SBI Main, (172, 180), 1],
  [SBI Main, (172, 180), 1],
  [Old Jail Road Jn, (182, 198), 1],
  [Vishakapatnam - 530020 Hereinafter, (200, 234), 1],
  [the LESSOR, (245, 255), 1],
  [LESSOR, (249, 255), 1],
  [which expression, (257, 273), 1],
  [the context, (306, 317), 1],
  [his heirs, (337, 346), 1],
  [executors, (348, 357), 1],
  [representatives, (359, 374), 1],
  [assigns, (379, 386), 1],
  [the ONE PART, (391, 403), 1],
  [And: V.V.Ravi Kian S/o V.R.G.Sastry, A.S.Rao, (405, 449), 1],
  [Nagar, (450, 455), 1],
  [Nagar, (450, 455), 1],
  [Hyderabad Andhra Pradesh.-36, (457, 485), 1],
  [Hyderabad Andhra, (457, 473), 1],
  [Hereinafter, (486, 497), 1],
  [the LESSEE, (505, 515), 1],
  [Which expression, (517, 533), 1],
  [the context, (566, 577), 1],
  [his executors, (598, 611), 1],
  [representatives, (613, 628), 1],
  [assigns, (633, 640), 1],
  [the OTHER PART, (645, 659), 1],
  [WITNESSES AS FOLLOWS, (662, 682), 1],
  [the Lessor, (692, 702), 1],
  [the absolute owner, (706, 724), 1],
  [the Fourth Floor residential premises, (728, 765), 1],
  [No:407A, (774, 781), 1],
  [T.C.Palya Main Road, (783, 802), 1],
  [Ram, (804, 807), 1],
  [murthy nagar, (808, 820), 1],
  [Bangalore-16, (822, 834), 1],
  [the Schedule, (869, 881), 1],
  [Schedule, (873, 881), 1],
  [hereinafter, (905, 916), 1],
  [the Schedule Property, (932, 953), 1],
  [the Schedule Property, (932, 953), 1],
  [the Lessor, (964, 974), 1],
  [a lease, (995, 1002), 1],
  [the said premises, (1006, 1023), 1],
  [the Lessee, (1027, 1037), 1],
  [Lessee, (1031, 1037), 1],
  [the following terms, (1044, 1063), 1],
  [conditions, (1068, 1078), 1],
  [DURATION, (1081, 1089), 1],
  [The duration, (1091, 1103), 1],
  [the Lease, (1107, 1116), 1],
  [Lease, (1111, 1116), 1],
  [a period, (1130, 1138), 1],
  [11 (Eleven) months, (1142, 1160), 1],
  [1st April, (1177, 1186), 1],
  [renewal, (1210, 1217), 1],
  [mutually agreed terms, (1235, 1256), 1],
  [conditions, (1261, 1271), 1],
  [the Lessor, (1275, 1285), 1],
  [the Lessee, (1290, 1300), 1],
  [an enhancement, (1306, 1320), 1],
  [the monthly rent, (1329, 1345), 1],
  [RENT, (1348, 1352), 1],
  [The monthly rent, (1354, 1370), 1],
  [the Lessee, (1382, 1392), 1],
  [Lessee, (1386, 1392), 1],
  [the LESSOR, (1396, 1406), 1],
  [the Schedule Property, (1411, 1432), 1],
  [Schedule Property, (1415, 1432), 1],
  [(Nine thousand and two hundred rupees, (1454, 1491), 1],
  [This amount, (1499, 1510), 1],
  [tenth day, (1544, 1553), 1],
  [subsequent month, (1557, 1573), 1],
  [ELECTRICITY, (1576, 1587), 1],
  [WATER CHARGES, (1592, 1605), 1],
  [The Lessee, (1607, 1617), 1],
  [Lessee, (1611, 1617), 1],
  [the Electricity charges, (1628, 1651), 1],
  [the concerned department, (1655, 1679), 1],
  [regularly

   INTERNAL MAINTENANCE, (1680, 1711), 1],
  [INTERNAL, (1691, 1699), 1],
  [The Lessee, (1713, 1723), 1],
  [Lessee, (1717, 1723), 1],
  [the Schedule Property, (1739, 1760), 1],
  [the Schedule Property, (1739, 1760), 1],
  [a state, (1764, 1771), 1],
  [good order, (1775, 1785), 1],
  [condition, (1790, 1799), 1],
  [any damage, (1820, 1830), 1],
  [disfigurement, (1834, 1847), 1],
  [the schedule property, (1851, 1872), 1],
  [fair wear, (1899, 1908), 1],
  [tear, (1913, 1917), 1],
  [DAMAGES, (1931, 1938), 1],
  [It, (1940, 1942), 1],
  [any damages, (1958, 1969), 1],
  [the Lessee, (1980, 1990), 1],
  [the Schedule Property, (1994, 2015), 1],
  [the Lessee, (2038, 2048), 1],
  [Lessee, (2042, 2048), 1],
  [USER, (2060, 2064), 1],
  [USER, (2060, 2064), 1],
  [The Schedule Property, (2066, 2087), 1],
  [the Lessee, (2105, 2115), 1],
  [Lessee, (2109, 2115), 1],
  [residential purpose, (2125, 2144), 1],
  [any business, (2186, 2198), 1],
  [occupation, (2202, 2212), 1],
  [any unlawful purpose, (2216, 2236), 1],
  [DEPOSIT, (2239, 2246), 1],
  [The Lessee, (2248, 2258), 1],
  [Lessee, (2252, 2258), 1],
  [a sum, (2268, 2273), 1],
  [Rs, (2277, 2279), 1],
  [(Rs, (2290, 2293), 1],
  [way, (2320, 2323), 1],
  [cash, (2327, 2331), 1],
  [Security Deposit, (2335, 2351), 1],
  [Security Deposit, (2335, 2351), 1],
  [The same amount, (2353, 2368), 1],
  [the Lessor, (2392, 2402), 1],
  [the Lessee, (2406, 2416), 1],
  [any interest, (2425, 2437), 1],
  [the time, (2441, 2449), 1],
  [the Schedule Premises, (2462, 2483), 1],
  [TERMINATION, (2486, 2497), 1],
  [LEASE, (2501, 2506), 1],
  [Either party, (2508, 2520), 1],
  [one month notice, (2530, 2546), 1],
  [this Lease agreement, (2571, 2591), 1],
  [what, (2610, 2614), 1],
  [the agreement, (2632, 2645), 1],
  [the Lessor, (2666, 2676), 1],
  [Lessor, (2670, 2676), 1],
  [the Lessee, (2681, 2691), 1],
  [Lessee, (2685, 2691), 1],
  [default, (2698, 2705), 1],
  [the payment, (2709, 2720), 1],
  [the rent, (2724, 2732), 1],
  [and/or other charges, (2733, 2753), 1],
  [the Lessee, (2804, 2814), 1],
  [Lessee, (2808, 2814), 1],
  [breach, (2823, 2829), 1],
  [any terms, (2833, 2842), 1],
  [conditions, (2847, 2857), 1],
  [this agreement, (2861, 2875), 1],
  [SCHEDULE PROPERTY Fourth Floor, (2878, 2908), 1],
  [the residential premises, (2912, 2936), 1],
  [HNO:407 A, (2949, 2958), 1],
  [T.C. Palya Main Road, (2960, 2980), 1],
  [murthy nagar, (2986, 2998), 1],
  [Bangalore-560037, (3000, 3016), 1],
  [three Bedrooms, (3032, 3046), 1],
  [hall, (3048, 3052), 1],
  [Toilet, (3076, 3082), 1],
  [Toilet, (3076, 3082), 1],
  [Bathrooms, (3087, 3096), 1],
  [Bathrooms, (3087, 3096), 1],
  [Fittings, (3099, 3107), 1],
  [Fittings, (3099, 3107), 1],
  [Fixtures, (3112, 3120), 1],
  [WITNESS, (3125, 3132), 1],
  [the parties, (3141, 3152), 1],
  [this agreement, (3167, 3181), 1],
  [the presence, (3185, 3197), 1],
  [the following witnesses, (3201, 3224), 1],
  [the day, (3228, 3235), 1],
  [month, (3237, 3242), 1],
  [year, (3247, 3251), 1]]}

In [54]:
def extract_date_spans(text):
    months_and_abbr = '|'.join('january february march april may june july august september october november december'.split())
    months_and_abbr += '|'+'|'.join('jan feb mar apr may jun jul aug sept sep oct nov dec'.split())

    regex_pattern1 = r'(\d{1,4})(.{0,10}?)('+months_and_abbr+')(.{0,5}?)(\d{4})'
    regex_pattern2 = r'(\d{1,4}([.\-/])\d{1,2}([.\-/])\d{1,4})'
    
    span_collection1 = get_index_of(regex_pattern1, [text])
    span_collection2 = get_index_of(regex_pattern2, [text])
    
    span_collection1.extend(span_collection2)
    span_collection1.sort(key=lambda x: x[1][0])
    return span_collection1

In [59]:
def get_index_of(regex_pattern=None, subject_strings=None):    
#     print(subject_string, regex_pattern)
    j=0;
    extracted_texts_and_span = []
    for ind, subject_string in enumerate(subject_strings):
#         print(subject_string)
        for i in re.finditer(regex_pattern, subject_string.lower()):
            j+=1
            # print(f'-->in:ind {ind} At:', i.start(), i.end(), 'extracted', i.group())
            extracted_texts_and_span.append([i.group(0), (i.start(), i.end()), ind])
#             extracted_texts_and_span.append(i)
            
    # print(j)
    return extracted_texts_and_span

In [60]:
extract_date_spans(one_doc_full_text)

[['1st may 2005', (85, 97), 0],
 ['10-12-1', (142, 149), 0],
 ['1st april 2010', (1177, 1191), 0]]

In [57]:
import re